// Mega platform catalog for username presence checks.
// kind 'page'  -> profile-URL probe with 404-marker scan (best-effort, confirm manually)
// kind 'api'   -> free public JSON API (reliable verdict)
// Labels mirror the DataVoid-style module taxonomy.
const P = (name, domain, label, url, extra = {}) => ({ name, domain, label, kind: 'page', url, ...extra });
const A = (name, domain, label, url, found, extra = {}) => ({ name, domain, label, kind: 'api', url, found, ...extra });

const PLATFORMS = [
  // ---- reliable free APIs ----
  A('GitHub', 'github.com', 'Development', (u) => `https://api.github.com/users/${encodeURIComponent(u)}`, (r) => r.status === 200 && !!r.data?.login),
  A('GitLab', 'gitlab.com', 'Development', (u) => `https://gitlab.com/api/v4/users?username=${encodeURIComponent(u)}`, (r) => r.status === 200 && Array.isArray(r.data) && r.data.length > 0),
  A('Reddit', 'reddit.com', 'Community', (u) => `https://www.reddit.com/user/${encodeURIComponent(u)}/about.json`, (r) => r.status === 200 && !!r.data?.data?.name),
  A('HackerNews', 'news.ycombinator.com', 'Community', (u) => `https://hacker-news.firebaseio.com/v0/user/${encodeURIComponent(u)}.json`, (r) => r.status === 200 && !!r.data?.id),
  A('Dev.to', 'dev.to', 'Development', (u) => `https://dev.to/api/articles?username=${encodeURIComponent(u)}&per_page=1`, (r) => r.status === 200 && Array.isArray(r.data)),
  A('Keybase', 'keybase.io', 'Security', (u) => `https://keybase.io/_/api/1.0/user/lookup.json?usernames=${encodeURIComponent(u)}&fields=basics`, (r) => r.status === 200 && Array.isArray(r.data?.them) && r.data.them.length > 0),
  A('Chess.com', 'chess.com', 'Gaming', (u) => `https://api.chess.com/pub/player/${encodeURIComponent(u.toLowerCase())}`, (r) => r.status === 200 && !!r.data?.username),
  A('Lichess', 'lichess.org', 'Gaming', (u) => `https://lichess.org/api/user/${encodeURIComponent(u)}`, (r) => r.status === 200 && !!r.data?.username),
  A('Minecraft', 'namemc.com', 'Gaming', (u) => `https://api.mojang.com/users/profiles/minecraft/${encodeURIComponent(u)}`, (r) => r.status === 200 && !!r.data?.id),
  A('Bluesky', 'bsky.app', 'Social Media', (u) => `https://public.api.bsky.app/xrpc/app.bsky.actor.getProfile?actor=${encodeURIComponent(u)}`, (r) => r.status === 200 && !!r.data?.handle),
  A('Mastodon.social', 'joinmastodon.org', 'Social Media', (u) => `https://mastodon.social/api/v1/accounts/lookup?acct=${encodeURIComponent(u)}`, (r) => r.status === 200 && !!r.data?.username),
  A('Gravatar', 'gravatar.com', 'Profile', (u) => `https://en.gravatar.com/${encodeURIComponent(u)}.json`, (r) => r.status === 200 && !!r.data?.entry),
  A('npm', 'npmjs.com', 'Development', (u) => `https://www.npmjs.com/~${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('not found')),
  A('PyPI', 'pypi.org', 'Development', (u) => `https://pypi.org/user/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('NuGet', 'nuget.org', 'Development', (u) => `https://www.nuget.org/profiles/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('not found')),
  A('Docker Hub', 'hub.docker.com', 'Development', (u) => `https://hub.docker.com/v2/users/${encodeURIComponent(u)}/`, (r) => r.status === 200 && !!r.data?.username),
  A('SourceForge', 'sourceforge.net', 'Development', (u) => `https://sourceforge.net/users/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Codeberg', 'codeberg.org', 'Development', (u) => `https://codeberg.org/api/v1/users/${encodeURIComponent(u)}`, (r) => r.status === 200 && !!r.data?.login),
  A('Launchpad', 'launchpad.net', 'Development', (u) => `https://launchpad.net/~${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('not found')),
  A('Wikipedia', 'wikipedia.org', 'Reference', (u) => `https://en.wikipedia.org/w/api.php?action=query&list=users&ususers=${encodeURIComponent(u)}&format=json&origin=*`, (r) => r.status === 200 && Array.isArray(r.data?.query?.users) && !r.data.query.users[0]?.missing),
  A('OpenStreetMap', 'openstreetmap.org', 'Maps', (u) => `https://www.openstreetmap.org/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('TryHackMe', 'tryhackme.com', 'Security', (u) => `https://tryhackme.com/p/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('HackerOne', 'hackerone.com', 'Security', (u) => `https://hackerone.com/${encodeURIComponent(u)}?type=user`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Exercism', 'exercism.org', 'Education', (u) => `https://exercism.org/profiles/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('freeCodeCamp', 'freecodecamp.org', 'Education', (u) => `https://www.freecodecamp.org/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Codecademy', 'codecademy.com', 'Education', (u) => `https://www.codecademy.com/profiles/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Duolingo', 'duolingo.com', 'Education', (u) => `https://www.duolingo.com/profile/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Scratch', 'mit.edu', 'Education', (u) => `https://api.scratch.mit.edu/users/${encodeURIComponent(u)}/`, (r) => r.status === 200 && !!r.data?.username),
  A('eBay', 'ebay.com', 'Marketplace', (u) => `https://www.ebay.com/usr/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Etsy', 'etsy.com', 'Marketplace', (u) => `https://www.etsy.com/people/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('error')),
  A('Redbubble', 'redbubble.com', 'Shopping', (u) => `https://www.redbubble.com/people/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Patreon', 'patreon.com', 'Donations', (u) => `https://www.patreon.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Ko-fi', 'ko-fi.com', 'Donations', (u) => `https://ko-fi.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('BuyMeACoffee', 'buymeacoffee.com', 'Donations', (u) => `https://www.buymeacoffee.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Kickstarter', 'kickstarter.com', 'Crowdfunding', (u) => `https://www.kickstarter.com/profile/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('OpenCollective', 'opencollective.com', 'Crowdfunding', (u) => `https://opencollective.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Liberapay', 'liberapay.com', 'Payments', (u) => `https://liberapay.com/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Letterboxd', 'letterboxd.com', 'Entertainment', (u) => `https://letterboxd.com/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').includes('Not Found')),
  A('Trakt', 'trakt.tv', 'Entertainment', (u) => `https://trakt.tv/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('SIMKL', 'simkl.com', 'Entertainment', (u) => `https://simkl.com/users/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('AniList', 'anilist.co', 'Entertainment', (u) => `https://anilist.co/user/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').includes('Not Found')),
  A('MyAnimeList', 'myanimelist.com', 'Entertainment', (u) => `https://myanimelist.net/profile/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('Not Found')),
  A('Anime-Planet', 'anime-planet.com', 'Entertainment', (u) => `https://www.anime-planet.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Backloggd', 'backloggd.com', 'Gaming', (u) => `https://www.backloggd.com/u/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Grouvee', 'grouvee.com', 'Gaming', (u) => `https://www.grouvee.com/user/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Speedrun.com', 'speedrun.com', 'Gaming', (u) => `https://www.speedrun.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('Not Found')),
  A('BoardGameGeek', 'boardgamegeek.com', 'Gaming', (u) => `https://boardgamegeek.com/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Last.fm', 'last.fm', 'Music', (u) => `https://www.last.fm/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('404')),
  A('Discogs', 'discogs.com', 'Music', (u) => `https://www.discogs.com/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('SoundCloud', 'soundcloud.com', 'Music', (u) => `https://soundcloud.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Mixcloud', 'mixcloud.com', 'Music', (u) => `https://www.mixcloud.com/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Audiomack', 'audiomack.com', 'Music', (u) => `https://audiomack.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Setlist.fm', 'setlist.fm', 'Music', (u) => `https://www.setlist.fm/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Songkick', 'songkick.com', 'Music', (u) => `https://www.songkick.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('ConcertArchives', 'concertarchives.org', 'Music', (u) => `https://www.concertarchives.org/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Behance', 'behance.net', 'Creative', (u) => `https://www.behance.net/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('404')),
  A('Dribbble', 'dribbble.com', 'Creative', (u) => `https://dribbble.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Figma', 'figma.com', 'Creative', (u) => `https://www.figma.com/@${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('ArtStation', 'artstation.com', 'Creative', (u) => `https://www.artstation.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('500px', '500px.com', 'Photography', (u) => `https://500px.com/p/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Unsplash', 'unsplash.com', 'Photography', (u) => `https://unsplash.com/@${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('Not Found')),
  A('Pexels', 'pexels.com', 'Photography', (u) => `https://www.pexels.com/@${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('VSCO', 'vsco.co', 'Photography', (u) => `https://vsco.co/${encodeURIComponent(u)}/gallery`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Imgur', 'imgur.com', 'Photography', (u) => `https://imgur.com/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('About.me', 'about.me', 'Profile', (u) => `https://about.me/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Linktree', 'linktr.ee', 'Profile', (u) => `https://linktr.ee/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Beacons', 'beacons.ai', 'Profile', (u) => `https://beacons.ai/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Bio.link', 'bio.link', 'Profile', (u) => `https://bio.link/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('AllMyLinks', 'allmylinks.com', 'Profile', (u) => `https://allmylinks.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('HuggingFace', 'huggingface.co', 'AI', (u) => `https://huggingface.co/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('404')),
  A('Civitai', 'civitai.com', 'AI', (u) => `https://civitai.com/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Kaggle', 'kaggle.com', 'AI', (u) => `https://www.kaggle.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('404')),
  A('Codeforces', 'codeforces.com', 'Development', (u) => `https://codeforces.com/profile/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Codewars', 'codewars.com', 'Development', (u) => `https://www.codewars.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Codechef', 'codechef.com', 'Development', (u) => `https://www.codechef.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('Not Found')),
  A('Topcoder', 'topcoder.com', 'Development', (u) => `https://profiles.topcoder.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('SPOJ', 'spoj.com', 'Development', (u) => `https://www.spoj.com/users/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('HackerEarth', 'hackerearth.com', 'Development', (u) => `https://www.hackerearth.com/@${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Replit', 'replit.com', 'Development', (u) => `https://replit.com/@${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Codepen', 'codepen.io', 'Development', (u) => `https://codepen.io/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').includes('404')),
  A('Glitch', 'glitch.com', 'Development', (u) => `https://glitch.com/@${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Observable', 'observablehq.com', 'Development', (u) => `https://observablehq.com/@${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Hashnode', 'hashnode.com', 'Development', (u) => `https://hashnode.com/@${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Lobsters', 'lobste.rs', 'Community', (u) => `https://lobste.rs/u/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('LiveJournal', 'livejournal.com', 'Community', (u) => `https://${encodeURIComponent(u)}.livejournal.com/profile`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Dreamwidth', 'dreamwidth.org', 'Community', (u) => `https://${encodeURIComponent(u)}.dreamwidth.org/profile`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Disqus', 'disqus.com', 'Community', (u) => `https://disqus.com/by/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').includes('404')),
  A('Wattpad', 'wattpad.com', 'Community', (u) => `https://www.wattpad.com/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('ArchiveOfOurOwn', 'archiveofourown.org', 'Community', (u) => `https://archiveofourown.org/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('NaNoWriMo', 'nanowrimo.org', 'Community', (u) => `https://nanowrimo.org/participants/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('OpenLibrary', 'openlibrary.org', 'Reference', (u) => `https://openlibrary.org/people/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('LibraryThing', 'librarything.com', 'Reference', (u) => `https://www.librarything.com/profile/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('iNaturalist', 'inaturalist.org', 'Outdoor', (u) => `https://www.inaturalist.org/people/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Zooniverse', 'zooniverse.org', 'Reference', (u) => `https://www.zooniverse.org/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Couchsurfing', 'couchsurfing.com', 'Travel', (u) => `https://www.couchsurfing.com/people/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('FindPenguins', 'findpenguins.com', 'Travel', (u) => `https://findpenguins.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('TheDyrt', 'thedyrt.com', 'Travel', (u) => `https://thedyrt.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Instructables', 'instructables.com', 'DIY', (u) => `https://www.instructables.com/member/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').includes('404')),
  A('Thingiverse', 'thingiverse.com', 'DIY', (u) => `https://www.thingiverse.com/${encodeURIComponent(u)}/designs`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('MyMiniFactory', 'myminifactory.com', 'DIY', (u) => `https://www.myminifactory.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Hackster', 'hackster.io', 'DIY', (u) => `https://www.hackster.io/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('BringATrailer', 'bringatrailer.com', 'Motors', (u) => `https://bringatrailer.com/member/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Pinkbike', 'pinkbike.com', 'Fitness', (u) => `https://www.pinkbike.com/u/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('BodySpace', 'bodybuilding.com', 'Fitness', (u) => `https://bodyspace.bodybuilding.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Monkeytype', 'monkeytype.com', 'Gaming', (u) => `https://monkeytype.com/profile/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Sporcle', 'sporcle.com', 'Gaming', (u) => `https://www.sporcle.com/user/${encodeURIComponent(u)}/people`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('FACEIT', 'faceit.com', 'Gaming', (u) => `https://www.faceit.com/en/players/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('FortniteTracker', 'fortnite.tracker.network', 'Gaming', (u) => `https://fortnite.tracker.network/fortnite/profile/all/${encodeURIComponent(u)}/overview`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('MuckRack', 'muckrack.com', 'News', (u) => `https://muckrack.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Change.org', 'change.org', 'Civic', (u) => `https://www.change.org/u/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('WikiTree', 'wikitree.com', 'Reference', (u) => `https://www.wikitree.com/wiki/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Bible.com', 'bible.com', 'Reference', (u) => `https://www.bible.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('AllRecipes', 'allrecipes.com', 'Food', (u) => `https://www.allrecipes.com/cook/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Untappd', 'untappd.com', 'Food', (u) => `https://untappd.com/user/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Vivino', 'vivino.com', 'Wine', (u) => `https://www.vivino.com/users/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Fiverr', 'fiverr.com', 'Professional', (u) => `https://www.fiverr.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Freelancer', 'freelancer.com', 'Professional', (u) => `https://www.freelancer.com/u/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Contra', 'contra.com', 'Professional', (u) => `https://contra.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Wellfound', 'wellfound.com', 'Professional', (u) => `https://wellfound.com/u/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Poshmark', 'poshmark.com', 'Shopping', (u) => `https://poshmark.com/closet/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Depop', 'depop.com', 'Shopping', (u) => `https://www.depop.com/${encodeURIComponent(u)}/`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('Grailed', 'grailed.com', 'Shopping', (u) => `https://www.grailed.com/${encodeURIComponent(u)}`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),
  A('LeagueOfComicGeeks', 'leagueofcomicgeeks.com', 'Entertainment', (u) => `https://leagueofcomicgeeks.com/profile/${encodeURIComponent(u)}/comics`, (r, body) => r.status === 200 && !(body || '').toLowerCase().includes('not found')),

  // ---- subdomain-presence probes ----
  P('Tumblr', 'tumblr.com', 'Social Media', (u) => `https://${encodeURIComponent(u)}.tumblr.com/`),
  P('Blogspot', 'blogspot.com', 'Community', (u) => `https://${encodeURIComponent(u)}.blogspot.com/`),
  P('WordPress', 'wordpress.com', 'Website', (u) => `https://${encodeURIComponent(u)}.wordpress.com/`),
  P('Substack', 'substack.com', 'Community', (u) => `https://${encodeURIComponent(u)}.substack.com/`),
  P('Bearblog', 'bearblog.dev', 'Community', (u) => `https://${encodeURIComponent(u)}.bearblog.dev/`),
  P('GitHub Pages', 'github.io', 'Development', (u) => `https://${encodeURIComponent(u)}.github.io/`),

  // ---- best-effort page probes (confirm manually) ----
  P('Twitter/X', 'x.com', 'Social Media', (u) => `https://x.com/${encodeURIComponent(u)}`),
  P('Instagram', 'instagram.com', 'Social Media', (u) => `https://www.instagram.com/${encodeURIComponent(u)}/`),
  P('TikTok', 'tiktok.com', 'Social Media', (u) => `https://www.tiktok.com/@${encodeURIComponent(u)}`),
  P('YouTube', 'youtube.com', 'Entertainment', (u) => `https://www.youtube.com/@${encodeURIComponent(u)}`),
  P('Twitch', 'twitch.tv', 'Gaming', (u) => `https://www.twitch.tv/${encodeURIComponent(u)}`),
  P('Kick', 'kick.com', 'Gaming', (u) => `https://kick.com/${encodeURIComponent(u)}`),
  P('Rumble', 'rumble.com', 'Entertainment', (u) => `https://rumble.com/user/${encodeURIComponent(u)}`),
  P('Odysee', 'odysee.com', 'Entertainment', (u) => `https://odysee.com/@${encodeURIComponent(u)}`),
  P('BitChute', 'bitchute.com', 'Entertainment', (u) => `https://www.bitchute.com/channel/${encodeURIComponent(u)}/`),
  P('Vimeo', 'vimeo.com', 'Entertainment', (u) => `https://vimeo.com/${encodeURIComponent(u)}`),
  P('Dailymotion', 'dailymotion.com', 'Entertainment', (u) => `https://www.dailymotion.com/${encodeURIComponent(u)}`),
  P('Snapchat', 'snapchat.com', 'Social Media', (u) => `https://www.snapchat.com/add/${encodeURIComponent(u)}`),
  P('Telegram', 'telegram.org', 'Communication', (u) => `https://t.me/${encodeURIComponent(u)}`),
  P('VK', 'vk.com', 'Social Media', (u) => `https://vk.com/${encodeURIComponent(u)}`),
  P('OK.ru', 'ok.ru', 'Social Media', (u) => `https://ok.ru/profile/${encodeURIComponent(u)}`),
  P('Pinterest', 'pinterest.com', 'Social Media', (u) => `https://www.pinterest.com/${encodeURIComponent(u)}/`),
  P('LinkedIn', 'linkedin.com', 'Professional', (u) => `https://www.linkedin.com/in/${encodeURIComponent(u)}`),
  P('Threads', 'threads.com', 'Social Media', (u) => `https://www.threads.com/@${encodeURIComponent(u)}`),
  P('Truth Social', 'truthsocial.com', 'Social Media', (u) => `https://truthsocial.com/@${encodeURIComponent(u)}`),
  P('Gab', 'gab.com', 'Social Media', (u) => `https://gab.com/${encodeURIComponent(u)}`),
  P('Minds', 'minds.com', 'Social Media', (u) => `https://www.minds.com/${encodeURIComponent(u)}/`),
  P('Gettr', 'gettr.com', 'Social Media', (u) => `https://gettr.com/user/${encodeURIComponent(u)}`),
  P('Medium', 'medium.com', 'Community', (u) => `https://medium.com/@${encodeURIComponent(u)}`),
  P('Quora', 'quora.com', 'Community', (u) => `https://www.quora.com/profile/${encodeURIComponent(u)}`),
  P('Fandom', 'fandom.com', 'Entertainment', (u) => `https://community.fandom.com/wiki/Special:Contributions/${encodeURIComponent(u)}`),
  P('Tumblr Search', 'tumblr.com', 'Social Media', (u) => `https://www.tumblr.com/search/${encodeURIComponent(u)}`, { note: 'search fallback' }),
  P('Spotify', 'spotify.com', 'Music', (u) => `https://open.spotify.com/user/${encodeURIComponent(u)}`),
  P('BandLab', 'bandlab.com', 'Music', (u) => `https://www.bandlab.com/${encodeURIComponent(u)}`),
  P('Genius', 'genius.com', 'Music', (u) => `https://genius.com/artists/${encodeURIComponent(u)}`),
  P('RateYourMusic', 'rateyourmusic.com', 'Music', (u) => `https://rateyourmusic.com/~${encodeURIComponent(u)}`),
  P('Steam', 'steam.com', 'Gaming', (u) => `https://steamcommunity.com/id/${encodeURIComponent(u)}`),
  P('PSN Profiles', 'psnprofiles.com', 'Gaming', (u) => `https://psnprofiles.com/${encodeURIComponent(u)}`),
  P('Xbox Gamertag', 'xboxgamertag.com', 'Gaming', (u) => `https://www.xboxgamertag.com/search/${encodeURIComponent(u)}`, { note: 'search fallback' }),
  P('Exophase', 'exophase.com', 'Gaming', (u) => `https://www.exophase.com/gamer/${encodeURIComponent(u)}/`),
  P('HackerRank', 'hackerrank.com', 'Development', (u) => `https://www.hackerrank.com/${encodeURIComponent(u)}`),
  P('Udemy', 'udemy.com', 'Education', (u) => `https://www.udemy.com/user/${encodeURIComponent(u)}/`),
  P('TeamTreehouse', 'teamtreehouse.com', 'Education', (u) => `https://teamtreehouse.com/${encodeURIComponent(u)}`),
  P('HelloPoetry', 'hellopoetry.com', 'Community', (u) => `https://hellopoetry.com/${encodeURIComponent(u)}/`),
  P('Inkitt', 'inkitt.com', 'Community', (u) => `https://www.inkitt.com/${encodeURIComponent(u)}`),
  P('Quotev', 'quotev.com', 'Community', (u) => `https://www.quotev.com/${encodeURIComponent(u)}`),
  P('Literal', 'literal.club', 'Reference', (u) => `https://literal.club/${encodeURIComponent(u)}`),
  P('Hardcover', 'hardcover.app', 'Reference', (u) => `https://hardcover.app/@${encodeURIComponent(u)}`),
  P('Polarsteps', 'polarsteps.com', 'Travel', (u) => `https://www.polarsteps.com/${encodeURIComponent(u)}`),
  P('Cults3D', 'cults3d.com', 'DIY', (u) => `https://cults3d.com/en/creators/${encodeURIComponent(u)}`),
  P('Flipboard', 'flipboard.com', 'News', (u) => `https://flipboard.com/@${encodeURIComponent(u)}`),
  P('OpenSea', 'opensea.io', 'Crypto', (u) => `https://opensea.io/${encodeURIComponent(u)}`),
  P('QRZ (ham)', 'qrz.com', 'Reference', (u) => `https://www.qrz.com/db/${encodeURIComponent(u.toUpperCase())}`),
  P('Sporcle Groups', 'sporcle.com', 'Gaming', (u) => `https://www.sporcle.com/groups/${encodeURIComponent(u)}`, { note: 'group fallback' }),
];

const NOT_FOUND_MARKERS = [
  'not found', 'page not found', 'usernotfound', "couldn't find", 'could not find', 'this account doesn',
  'sorry, this page', 'profile not found', 'no longer available', 'does not exist', 'no longer exists',
  'user does not exist', 'nothing to see here', 'error 404', 'oops! that page', 'page you requested',
  'invalid username', 'unknown user', 'user not registered', 'no such user',
];

module.exports = { PLATFORMS, NOT_FOUND_MARKERS };
